apiVersion: v1
kind: PersistentVolume # Create PV 
metadata:
  name: pv # Sets PV name
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 20Gi # Sets PV's size
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/disk/vol1"
nodeAffinity:
  required:
    nodeSelectorTerms:
    - matchExpressions:
      - key: kubernetes.io/hostname
        operator: In
        values:
        - vps-732943eb