apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecrets.name }}
  namespace: {{ .Values.namespace }}
data:
  .dockerconfigjson: {{ .Values.imagePullSecrets.dockerconfigjson }}
type: kubernetes.io/dockerconfigjson